name: PrepBuddy Support Request
description: PrepBuddy Support Request
labels: ["v1-prepbuddy-co-in"]
assignees: 
  - joshua-d-terv-pro
projects: ["cloudops-one/2","cloudops-one/4"]
type: support
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out!
  - type: dropdown
    id: priority
    attributes:
      label: What is the priority?
      description: Choose one option
      multiple: true
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What support you need?
      description: Tell us where you got stuck up?
      placeholder: Tell us where you got stuck up..
    validations:
      required: true
